multilibtool_LIBRARIES += %D%/libcirclenewlib.a

%C%_libcirclenewlib_a_SOURCES = \
	%D%/chdir.cpp \
	%D%/chown.c \
	%D%/circlenetmap.cpp \
	%D%/environ.c \
	%D%/errno.c \
	%D%/execve.c \
	%D%/_exit.cpp \
	%D%/filetable.cpp \
	%D%/fork.c \
	%D%/getcwd.cpp \
	%D%/getpid.c \
	%D%/gettod.cpp \
	%D%/io.cpp \
	%D%/kill.c \
	%D%/link.c \
	%D%/mem.c \
	%D%/mkdir.cpp \
	%D%/netdb.cpp \
	%D%/pipe.cpp \
	%D%/poll.cpp \
	%D%/readlink.c \
	%D%/rename.cpp \
	%D%/sbrk.c \
	%D%/select.cpp \
	%D%/socketio.cpp \
	%D%/stat.cpp \
	%D%/statvfs.cpp \
	%D%/symlink.c \
	%D%/times.c \
	%D%/unlink.cpp \
	%D%/wait.c